### PR TITLE
Fix for some conversions to non-metric

### LINKED ISSUE #76: non-metric conversions not all working
It seems that the average speed, odometer, and energy consumption values are not working in non-metric mode.  The first two are just minor fixes.  The third is a math error.  I have a patch that works.  If given permission, I'll open a pull request.
[polestar_api_diff.txt](https://github.com/leeyuentuen/polestar_api/files/13854903/polestar_api_diff.txt)

### PR DESCRIPTION
**Pull request by carrel-gr**
Fixes #76

### CODE REVIEW

**Comment by dgomes** [comment]
This conversion must stop... it is handle by HA core, this is just duplication of efforts and is error prone.

Only one of the properties should be read and the other completely ignored

**Comment by carrel-gr** [comment]
How does one properly use the core to convert between metric and non-metric?  Odometer seems to be read as meters, most other distances are kilometers, and the efficiency is in kWh/100km which there doesn't seem to be a native unit for.  I'll happily try to help convert things to "the right way".  I'll look for some examples.  Can you point me at one?

> This conversion must stop... it is handle by HA core, this is just duplication of efforts and is error prone.
> 
> Only one of the properties should be read and the other completely ignored

**Comment by dgomes** [comment]
Similar to temperature:

https://developers.home-assistant.io/blog/2021/08/12/sensor_temperature_conversion

`native_value` , `native_unit_of_measurement` and device_class `SensorDeviceClass.DISTANCE`

**Comment by leeyuentuen** [comment]
no worries, i've already something ready for this. I'll commit them soon

**Comment by leeyuentuen** [comment]
i still need to test, but this should fix the non-metric issue

**Pull request closed without merging**
